M48
; DRILL file KiCad 10.0.4 date 2026-09-09T23:06:27
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-09T23:06:27+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.680
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.150
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.500
%
G90
G05
T1
X209.15Y-106.26
X216.35Y-106.26
T2
X239.15Y-90.675
T3
X260.15Y-90.675
T4
X182.0Y-86.575
X230.075Y-86.575
M30
